#!/bin/bash

# considering dropbox sync
OUTPUT_DIR="${HOME}/.maketex.d/"

#
CURRENT_LOCATION="`pwd`/"

# name of main TeX file.
if [ $# -eq 0 ]; then
    FILE_NAME_TEX="main.tex"
    FILE_LOCATION="$CURRENT_LOCATION"
else
	FILE_NAME_TEX="$1"
    FILE_LOCATION="${FILE_NAME_TEX%/*}/"
	FILE_NAME_TEX=${FILE_NAME_TEX##*/}
fi

# remove extention
case $FILE_NAME_TEX in
	*\.tex)
		FILE_NAME_NO_EXTENTION=`echo $FILE_NAME_TEX | sed -e "s/\.tex//"`
		echo $FILE_NAME_NO_EXTENTION
		;;
	*)
		FILE_NAME_NO_EXTENTION=$FILE_NAME_TEX
		;;
esac

# make output dir
if [ ! -d $OUTPUT_DIR ]; then
	mkdir -p $OUTPUT_DIR
fi

# module load
. extract.fnc

# png or pdf to eps.
gen_eps "${FILE_LOCATION}figures"

# main flow
flow_make_tex $OUTPUT_DIR $FILE_NAME_NO_EXTENTION $FILE_LOCATION